{{- range .Values.microservices }}
{{- if .serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "event-sourcing-microservices.serviceAccountName" . }}
  labels:
    {{ toYaml .image.labels | indent 4 }}
automountServiceAccountToken: {{ .serviceAccount.automount }}
---
{{- end }}
{{- end }}
