{{- range .Values.microservices -}}
{{- if .serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- include "event-sourcing-microservices.serviceAccountName" . }}
automountServiceAccountToken: {{ .serviceAccount.automount }}
{{- end }}
{{- end }}
